# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer', models.CharField(max_length=250)),
                ('department_name', models.CharField(max_length=500)),
                ('department_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('soldier_name', models.CharField(max_length=250)),
                ('is_baknaz_team', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship.Department')),
            ],
        ),
    ]
