# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='rank',
        ),
        migrations.AddField(
            model_name='soldier',
            name='tag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
