# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0003_singlerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlerecord',
            old_name='soldier_id',
            new_name='soldier_tag_field_0',
        ),
        migrations.AddField(
            model_name='singlerecord',
            name='soldier_tag_field_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlerecord',
            name='soldier_tag_field_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlerecord',
            name='soldier_tag_field_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singlerecord',
            name='time_stamp',
            field=models.DateTimeField(default='1999-31-12 23:59'),
        ),
    ]
