# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0004_auto_20161210_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlerecord',
            name='soldier_tag_field_0',
        ),
        migrations.RemoveField(
            model_name='singlerecord',
            name='soldier_tag_field_1',
        ),
        migrations.RemoveField(
            model_name='singlerecord',
            name='soldier_tag_field_2',
        ),
        migrations.RemoveField(
            model_name='singlerecord',
            name='soldier_tag_field_3',
        ),
        migrations.AddField(
            model_name='singlerecord',
            name='tag_string',
            field=models.CharField(default='0x00 0x00 0x00 0x00', max_length=20),
        ),
        migrations.AlterField(
            model_name='singlerecord',
            name='compartment',
            field=models.IntegerField(default=532),
        ),
    ]
