# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0007_auto_20161213_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlerecord',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
