# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0013_auto_20161214_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlerecord',
            name='time_stamp',
            field=models.CharField(max_length=250),
        ),
    ]
